import {
  User,
  Profile,
  Family,
  PaymentRecord,
  Receipt,
  NikahApplication,
  WelfareApplication,
  ZakahApplication,
  Certificate,
  EventItem,
  Announcement,
  Enquiry,
  NotificationItem,
  MahalSettings,
  AuditLogItem,
  CounsellingBooking,
  EducationGuidanceRegistration,
  BloodDonor,
  BloodRequest,
  DeathCertificateApplication,
  FinancialLedgerEntry,
  InstitutionFinancialSummary,
} from '../types';

export const INITIAL_SETTINGS: MahalSettings = {
  mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
  mahalNameMalayalam: 'നൂറുൽ ഹുദാ ജുമാ മസ്ജിദ് & മഹല്ല് ജമാഅത്ത്',
  registrationNumber: 'MHL-KL-KKD-2024/048',
  address: 'Noor-ul-Huda Masjid Road, West Hill, Kozhikode, Kerala 673005',
  phone: '+91 495 2381234',
  email: 'office@noorulhudamahal.org',
  whatsAppNumber: '919876543210',
  qaziName: 'Sayyid Munavvar Ali Shihab Thangal',
  presidentName: 'Janab P.K. Hameed Haji',
  secretaryName: 'C.M. Abdul Azeez Master',
  monthlyContributionDefault: 1000,
  paymentDueDay: 10,
  gracePeriodDays: 15,
  lateFee: 50,
};

export const DEMO_USERS: User[] = [
  {
    id: 'user-admin',
    email: 'admin@demo.mahalconnect.local',
    name: 'Usthad Abdul Rahman',
    role: 'ADMIN',
    phone: '+91 94471 23456',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-member-1',
    email: 'member@demo.mahalconnect.local',
    name: 'Ahamed Basheer',
    role: 'MEMBER',
    phone: '+91 98460 11223',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-nikah-staff',
    email: 'nikah@demo.mahalconnect.local',
    name: 'K.V. Moideen Kutty',
    role: 'NIKAH_STAFF',
    phone: '+91 98472 33445',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-welfare-staff',
    email: 'welfare@demo.mahalconnect.local',
    name: 'Dr. Faisal K.',
    role: 'WELFARE_STAFF',
    phone: '+91 94470 55667',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-zakah-staff',
    email: 'zakah@demo.mahalconnect.local',
    name: 'C.P. Hamza',
    role: 'ZAKAH_STAFF',
    phone: '+91 98461 77889',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'prof-1',
    userId: 'user-member-1',
    memberId: 'MHL-000124',
    membershipNumber: 'REG-2021-0124',
    name: 'Ahamed Basheer',
    nameMalayalam: 'അഹമ്മദ് ബഷീർ',
    gender: 'MALE',
    dateOfBirth: '1984-05-14',
    phone: '+91 98460 11223',
    email: 'member@demo.mahalconnect.local',
    address: 'Baitul Noor, Mosque Lane, West Hill, Kozhikode, 673005',
    occupation: 'Senior Accountant, Gulf Trading Co.',
    education: 'B.Com, M.Com',
    bloodGroup: 'O+ve',
    familyId: 'FAM-00042',
    familyRole: 'HEAD',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    membershipDate: '2021-03-15',
    membershipStatus: 'ACTIVE',
    monthlyContribution: 1000,
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    isPublicInDirectory: true,
  },
  {
    id: 'prof-2',
    userId: 'user-member-spouse',
    memberId: 'MHL-000125',
    membershipNumber: 'REG-2021-0125',
    name: 'Fathima Zeenath',
    nameMalayalam: 'ഫാത്തിമ സീനത്ത്',
    gender: 'FEMALE',
    dateOfBirth: '1988-11-20',
    phone: '+91 98460 11224',
    email: 'zeenath@example.com',
    address: 'Baitul Noor, Mosque Lane, West Hill, Kozhikode',
    occupation: 'Teacher, Crescent High School',
    education: 'B.Ed, M.A English',
    bloodGroup: 'B+ve',
    familyId: 'FAM-00042',
    familyRole: 'SPOUSE',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    membershipDate: '2021-03-15',
    membershipStatus: 'ACTIVE',
    monthlyContribution: 0,
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    isPublicInDirectory: false,
  },
  {
    id: 'prof-3',
    userId: 'user-member-son',
    memberId: 'MHL-000126',
    membershipNumber: 'REG-2021-0126',
    name: 'Mohammed Raihan',
    nameMalayalam: 'മുഹമ്മദ് റൈഹാൻ',
    gender: 'MALE',
    dateOfBirth: '2010-08-04',
    phone: '+91 98460 11223',
    email: 'raihan@example.com',
    address: 'Baitul Noor, Mosque Lane, West Hill, Kozhikode',
    occupation: 'Student (10th Standard)',
    education: 'High School',
    bloodGroup: 'O+ve',
    familyId: 'FAM-00042',
    familyRole: 'SON',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    membershipDate: '2021-03-15',
    membershipStatus: 'ACTIVE',
    monthlyContribution: 0,
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    isPublicInDirectory: false,
  },
  {
    id: 'prof-4',
    userId: 'user-member-daughter',
    memberId: 'MHL-000127',
    membershipNumber: 'REG-2021-0127',
    name: 'Aysha Nuha',
    nameMalayalam: 'ആയിഷ നുഹ',
    gender: 'FEMALE',
    dateOfBirth: '2015-02-18',
    phone: '+91 98460 11223',
    email: 'nuha@example.com',
    address: 'Baitul Noor, Mosque Lane, West Hill, Kozhikode',
    occupation: 'Student (5th Standard)',
    education: 'Primary School',
    bloodGroup: 'A+ve',
    familyId: 'FAM-00042',
    familyRole: 'DAUGHTER',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    membershipDate: '2021-03-15',
    membershipStatus: 'ACTIVE',
    monthlyContribution: 0,
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    isPublicInDirectory: false,
  },
];

export const INITIAL_FAMILIES: Family[] = [
  {
    id: 'fam-1',
    familyId: 'FAM-00042',
    familyName: 'Baitul Noor Family',
    houseName: 'Baitul Noor',
    headMemberId: 'MHL-000124',
    headName: 'Ahamed Basheer',
    address: 'Mosque Lane, West Hill, Kozhikode, 673005',
    phone: '+91 98460 11223',
    memberCount: 4,
    monthlyContribution: 1000,
    paymentStatus: 'PENDING',
  },
  {
    id: 'fam-2',
    familyId: 'FAM-00043',
    familyName: 'Al-Huda House',
    houseName: 'Al-Huda',
    headMemberId: 'MHL-000130',
    headName: 'K.P. Usman Haji',
    address: 'Beach Road, West Hill, Kozhikode',
    phone: '+91 94471 99887',
    memberCount: 6,
    monthlyContribution: 1500,
    paymentStatus: 'PAID',
  },
  {
    id: 'fam-3',
    familyId: 'FAM-00044',
    familyName: 'Darul Aman Family',
    houseName: 'Darul Aman',
    headMemberId: 'MHL-000135',
    headName: 'V.K. Sharafudheen',
    address: 'Bypass Jn, West Hill, Kozhikode',
    phone: '+91 98470 44556',
    memberCount: 5,
    monthlyContribution: 1000,
    paymentStatus: 'OVERDUE',
  },
  {
    id: 'fam-4',
    familyId: 'FAM-00045',
    familyName: 'Anugraha House',
    houseName: 'Anugraha Manzil',
    headMemberId: 'MHL-000140',
    headName: 'T.P. Mustafa Master',
    address: 'Post Office Road, West Hill, Kozhikode',
    phone: '+91 94472 66778',
    memberCount: 3,
    monthlyContribution: 1000,
    paymentStatus: 'PAID',
  },
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-2026-09',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    month: '2026-09',
    monthName: 'September 2026',
    amount: 1000,
    status: 'PENDING',
    dueDate: '2026-09-10',
    lateFee: 0,
  },
  {
    id: 'pay-2026-08',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    month: '2026-08',
    monthName: 'August 2026',
    amount: 1000,
    status: 'PAID',
    dueDate: '2026-08-10',
    paidDate: '2026-08-06',
    transactionId: 'TXN-RAZ-9823412',
    receiptNumber: 'RCT-2026-00084',
    paymentMethod: 'UPI',
  },
  {
    id: 'pay-2026-07',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    month: '2026-07',
    monthName: 'July 2026',
    amount: 1000,
    status: 'PAID',
    dueDate: '2026-07-10',
    paidDate: '2026-07-08',
    transactionId: 'TXN-RAZ-8711203',
    receiptNumber: 'RCT-2026-00072',
    paymentMethod: 'UPI',
  },
  {
    id: 'pay-2026-06',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    month: '2026-06',
    monthName: 'June 2026',
    amount: 1000,
    status: 'PAID',
    dueDate: '2026-06-10',
    paidDate: '2026-06-04',
    transactionId: 'TXN-NET-5412981',
    receiptNumber: 'RCT-2026-00061',
    paymentMethod: 'NET_BANKING',
  },
  {
    id: 'pay-2026-05',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    month: '2026-05',
    monthName: 'May 2026',
    amount: 1000,
    status: 'PAID',
    dueDate: '2026-05-10',
    paidDate: '2026-05-09',
    transactionId: 'TXN-UPI-3321908',
    receiptNumber: 'RCT-2026-00050',
    paymentMethod: 'UPI',
  },
  {
    id: 'pay-2026-04',
    memberId: 'MHL-000124',
    familyId: 'FAM-00042',
    month: '2026-04',
    monthName: 'April 2026',
    amount: 1000,
    status: 'PAID',
    dueDate: '2026-04-10',
    paidDate: '2026-04-03',
    transactionId: 'TXN-UPI-1192834',
    receiptNumber: 'RCT-2026-00038',
    paymentMethod: 'UPI',
  },
];

export const INITIAL_RECEIPTS: Receipt[] = [
  {
    receiptNumber: 'RCT-2026-00084',
    paymentId: 'pay-2026-08',
    memberId: 'MHL-000124',
    memberName: 'Ahamed Basheer',
    familyId: 'FAM-00042',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    monthName: 'August 2026',
    amount: 1000,
    paymentDate: '2026-08-06 11:24 AM',
    paymentMethod: 'UPI (GPay / PhonePe)',
    transactionId: 'TXN-RAZ-9823412',
    status: 'VERIFIED',
    signatureOfficer: 'C.M. Abdul Azeez (General Secretary)',
  },
  {
    receiptNumber: 'RCT-2026-00072',
    paymentId: 'pay-2026-07',
    memberId: 'MHL-000124',
    memberName: 'Ahamed Basheer',
    familyId: 'FAM-00042',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    monthName: 'July 2026',
    amount: 1000,
    paymentDate: '2026-07-08 04:12 PM',
    paymentMethod: 'UPI',
    transactionId: 'TXN-RAZ-8711203',
    status: 'VERIFIED',
    signatureOfficer: 'C.M. Abdul Azeez (General Secretary)',
  },
];

export const INITIAL_NIKAH_APPLICATIONS: NikahApplication[] = [
  {
    id: 'nikah-1',
    applicationNumber: 'NIK-2026-00124',
    applicantId: 'MHL-000124',
    applicantName: 'Ahamed Basheer',
    applicantPhone: '+91 98460 11223',
    applicantRelation: 'GUARDIAN',
    groomName: 'Sayyid Adil Hashim',
    groomAge: 27,
    groomDob: '1999-03-12',
    groomAddress: 'Hashim Villa, Kondotty, Malappuram',
    groomMahal: 'Kondotty Markaz Mahal Jama-ath',
    groomFatherName: 'Sayyid Hashim Thangal',
    groomMotherName: 'Sharifa Ummu Kulsum',
    groomOccupation: 'Software Architect',
    groomPhone: '+91 97451 22334',
    brideName: 'Fathima Safa Binte Basheer',
    brideAge: 24,
    brideDob: '2002-06-25',
    brideAddress: 'Baitul Noor, Mosque Lane, West Hill, Kozhikode',
    brideMahal: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    brideFatherName: 'Ahamed Basheer',
    brideMotherName: 'Fathima Zeenath',
    brideOccupation: 'Civil Engineer',
    bridePhone: '+91 98460 11228',
    waliName: 'Ahamed Basheer (Father)',
    waliRelation: 'FATHER',
    waliPhone: '+91 98460 11223',
    proposedDate: '2026-10-18',
    proposedTime: '11:30 AM',
    venue: 'Noor-ul-Huda Community Auditorium, West Hill',
    officerAssigned: 'Usthad Zainul Abideen Moulavi (Imam)',
    status: 'UNDER_VERIFICATION',
    documents: [
      { name: 'Bride Mahal NOC & Identity Proof', type: 'PDF', verified: true, url: '#' },
      { name: 'Groom Mahal Clearance Certificate', type: 'PDF', verified: true, url: '#' },
      { name: 'Aadhaar Cards of Groom & Bride', type: 'PDF', verified: true, url: '#' },
      { name: 'Pre-Marital Course Completion Certificate', type: 'PDF', verified: false, url: '#' },
    ],
    adminNotes: 'Groom mahal certificate verified with Kondotty secretary over phone. Pre-marital counseling doc pending verification.',
    createdAt: '2026-09-02',
    updatedAt: '2026-09-18',
  },
  {
    id: 'nikah-2',
    applicationNumber: 'NIK-2026-00120',
    applicantId: 'MHL-000130',
    applicantName: 'K.P. Usman Haji',
    applicantPhone: '+91 94471 99887',
    applicantRelation: 'GUARDIAN',
    groomName: 'Dr. Nabeel Usman',
    groomAge: 29,
    groomDob: '1997-01-15',
    groomAddress: 'Al-Huda House, Beach Road, West Hill',
    groomMahal: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    groomFatherName: 'K.P. Usman Haji',
    groomMotherName: 'Khadija Usman',
    groomOccupation: 'Pediatric Surgeon',
    groomPhone: '+91 94471 99889',
    brideName: 'Dr. Shahina Abdul Kareem',
    brideAge: 26,
    brideDob: '2000-09-10',
    brideAddress: 'Kareem Manzil, Nadakkavu, Kozhikode',
    brideMahal: 'Nadakkavu Town Juma Masjid',
    brideFatherName: 'Abdul Kareem P.',
    brideMotherName: 'Sufeera Kareem',
    brideOccupation: 'Dental Surgeon',
    bridePhone: '+91 98471 88990',
    waliName: 'Abdul Kareem P. (Father)',
    waliRelation: 'FATHER',
    waliPhone: '+91 98471 88990',
    proposedDate: '2026-09-28',
    proposedTime: '12:00 PM',
    venue: 'Noor-ul-Huda Juma Masjid Central Hall',
    officerAssigned: 'Sayyid Munavvar Ali Shihab Thangal (Qazi)',
    status: 'SCHEDULED',
    documents: [
      { name: 'Groom Identity & Clearance', type: 'PDF', verified: true },
      { name: 'Bride Mahal NOC', type: 'PDF', verified: true },
      { name: 'Pre-Marital Counseling Certificate', type: 'PDF', verified: true },
    ],
    adminNotes: 'Solemnization scheduled after Dhuhr prayer on 28th September 2026. Hall reserved.',
    certificateNumber: 'CERT-NIK-2026-00098',
    createdAt: '2026-08-20',
    updatedAt: '2026-09-15',
  },
];

export const INITIAL_WELFARE_APPLICATIONS: WelfareApplication[] = [
  {
    id: 'wel-1',
    applicationNumber: 'WEL-2026-00045',
    memberId: 'MHL-000124',
    applicantName: 'Ahamed Basheer',
    phone: '+91 98460 11223',
    familyId: 'FAM-00042',
    category: 'EDUCATION',
    amountRequested: 25000,
    amountApproved: 20000,
    description: 'Higher secondary educational merit scholarship assistance for daughter Aysha Nuha (Quran memorization and academic fees).',
    medicalOrInstituteName: 'Crescent Higher Secondary School, Kozhikode',
    status: 'APPROVED',
    reviewerNotes: 'Approved in August committee meeting. Fund disbursement scheduled.',
    submittedAt: '2026-08-12',
    processedAt: '2026-08-24',
  },
  {
    id: 'wel-2',
    applicationNumber: 'WEL-2026-00046',
    memberId: 'MHL-000135',
    applicantName: 'V.K. Sharafudheen',
    phone: '+91 98470 44556',
    familyId: 'FAM-00044',
    category: 'MEDICAL',
    amountRequested: 50000,
    description: 'Urgent kidney dialysis and medical equipment support for elderly mother (age 78).',
    medicalOrInstituteName: 'Government Medical College Hospital, Calicut',
    status: 'UNDER_REVIEW',
    reviewerNotes: 'Medical records under review by Dr. Faisal K. (Welfare in-charge).',
    submittedAt: '2026-09-14',
  },
];

export const INITIAL_ZAKAH_APPLICATIONS: ZakahApplication[] = [
  {
    id: 'zak-1',
    applicationNumber: 'ZAK-2026-00031',
    memberId: 'MHL-000155',
    applicantName: 'K. Zainaba',
    phone: '+91 98465 44332',
    familyId: 'FAM-00088',
    dependentsCount: 3,
    monthlyFamilyIncome: 4500,
    category: 'POOR',
    amountNeeded: 35000,
    amountDistributed: 35000,
    financialSituation: 'Widow raising two orphan school children with no permanent earning member in household.',
    status: 'COMPLETED',
    assessmentNotes: 'Case verified by local ward committee. Distributed via direct bank transfer from Mahal Zakah Fund.',
    submittedAt: '2026-07-10',
    distributionDate: '2026-07-28',
  },
  {
    id: 'zak-2',
    applicationNumber: 'ZAK-2026-00032',
    memberId: 'MHL-000162',
    applicantName: 'M.P. Abdulla',
    phone: '+91 94473 11220',
    familyId: 'FAM-00094',
    dependentsCount: 5,
    monthlyFamilyIncome: 6000,
    category: 'DEBT_STRICKEN',
    amountNeeded: 45000,
    financialSituation: 'Accumulated medical treatment debt following cardiac bypass surgery; unable to do manual labor.',
    status: 'DISTRIBUTION_SCHEDULED',
    assessmentNotes: 'Hospital debt bills verified. Scheduled for disbursement in upcoming Rabi-ul-Awwal Zakah round.',
    submittedAt: '2026-09-05',
    distributionDate: '2026-09-29',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    title: 'Mahal Annual General Body Meeting 2026',
    titleMalayalam: 'മഹല്ല് വാർഷിക പൊതുയോഗം 2026',
    description: 'Presentation of annual audited accounts, development works review, and election of new sub-committees.',
    descriptionMalayalam: 'വാർഷിക വരവ്-ചിലവ് കണക്കുകൾ അവതരിപ്പിക്കലും പുതിയ സബ് കമ്മിറ്റികളുടെ തിരഞ്ഞെടുപ്പും.',
    date: '2026-10-04',
    time: '04:30 PM (After Asr)',
    venue: 'Noor-ul-Huda Community Hall, West Hill',
    speakerOrChiefGuest: 'Sayyid Munavvar Ali Shihab Thangal',
    registeredCount: 142,
    registrationLimit: 250,
    isRegistrationOpen: true,
  },
  {
    id: 'evt-2',
    title: 'Community Free Health & Blood Donation Camp',
    titleMalayalam: 'സൗജന്യ മെഡിക്കൽ & രക്തദാന ക്യാമ്പ്',
    description: 'General health checkup, diabetes and blood pressure screening, cardiology consultation, and volunteer blood donation.',
    descriptionMalayalam: 'സൗജന്യ പരിശോധന, പ്രമേഹം, രക്തസമ്മർദ്ദം, ഹൃദ്രോഗ വിദഗ്ദ്ധരുടെ സേവനം, രക്തദാനം.',
    date: '2026-10-11',
    time: '08:30 AM - 01:30 PM',
    venue: 'Mahal Madrasa Complex Ground Floor',
    speakerOrChiefGuest: 'Dr. Faisal K. & Medical College Team',
    registeredCount: 88,
    registrationLimit: 150,
    isRegistrationOpen: true,
  },
  {
    id: 'evt-3',
    title: 'Youth Pre-Marital Life Skills Workshop',
    titleMalayalam: 'യുവജന പ്രീ-മാരിറ്റൽ കൗൺസിലിംഗ് ശില്പശാല',
    description: 'Comprehensive Islamic marital jurisprudence, emotional intelligence, financial planning, and family harmony workshop.',
    descriptionMalayalam: 'ഇസ്ലാമിക കുടുംബ ജീവിതം, ആശയവിനിമയം, സാമ്പത്തിക ഭദ്രത എന്നിവയെക്കുറിച്ചുള്ള ശില്പശാല.',
    date: '2026-10-25',
    time: '09:00 AM - 04:00 PM',
    venue: 'Conference Hall, Noor-ul-Huda Islamic Centre',
    speakerOrChiefGuest: 'Renowned Family Counselors & Scholars',
    registeredCount: 45,
    registrationLimit: 60,
    isRegistrationOpen: true,
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Urgent: Public Water Supply Maintenance Notice',
    titleMalayalam: 'പ്രധാനം: മഹല്ല് കുടിവെള്ള വിതരണ അറ്റകുറ്റപ്പണി',
    content: 'The central water pump tank cleaning will take place this Thursday. Please store necessary water in advance.',
    contentMalayalam: 'വ്യാഴാഴ്ച പള്ളിയിലെയും മഹല്ല് പൈപ്പ് ലൈനിലെയും ടാങ്ക് വൃത്തിയാക്കൽ നടക്കുന്നതിനാൽ ആവശ്യമായ വെള്ളം കരുതിവെക്കുക.',
    priority: 'URGENT',
    publishedDate: '2026-09-20',
    expiryDate: '2026-09-24',
    author: 'Mahal Development Committee',
  },
  {
    id: 'ann-2',
    title: 'Higher Education Merit Scholarships 2026-27 Application Open',
    titleMalayalam: 'ഉന്നത വിദ്യാഭ്യാസ മെറിറ്റ് സ്കോളർഷിപ്പ് അപേക്ഷ ക്ഷണിക്കുന്നു',
    content: 'SSLC, Plus Two, and Degree students scoring 90%+ marks can submit their marklists through the portal.',
    contentMalayalam: 'എസ്.എസ്.എൽ.സി, പ്ലസ് ടു പരീക്ഷകളിൽ ഉന്നത വിജയം കരസ്ഥമാക്കിയ മഹല്ലിലെ വിദ്യാർത്ഥികൾക്ക് സ്കോളർഷിപ്പിന് അപേക്ഷിക്കാം.',
    priority: 'IMPORTANT',
    publishedDate: '2026-09-15',
    expiryDate: '2026-10-15',
    author: 'Mahal Education Board',
  },
  {
    id: 'ann-3',
    title: 'Digital Portal Launch & Online Monthly Payments',
    titleMalayalam: 'മഹല്ല് കണക്റ്റ് ഡിജിറ്റൽ പോർട്ടൽ പ്രവർത്തനം ആരംഭിച്ചു',
    content: 'Members can now pay monthly contributions via UPI/Net Banking and download official verified receipts.',
    contentMalayalam: 'എല്ലാ മാസവരികളും ഇനി ഡിജിറ്റലായി അടയ്ക്കാനും രസീതുകൾ തത്സമയം ഡൗൺലോഡ് ചെയ്യാനും സാധിക്കും.',
    priority: 'NORMAL',
    publishedDate: '2026-09-01',
    author: 'President & General Secretary',
  },
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-1',
    enquiryNumber: 'ENQ-2026-00124',
    name: 'Rashid Ahammed',
    phone: '+91 97451 98765',
    email: 'rashid@example.com',
    category: 'NIKAH',
    message: 'Can we book the Noor-ul-Huda auditorium for a Nikah ceremony on November 15th Sunday afternoon?',
    status: 'IN_PROGRESS',
    assignedTo: 'K.V. Moideen Kutty (Nikah In-charge)',
    replyMessage: 'Hall is tentatively open on November 15th afternoon session. Please submit an online Nikah application.',
    createdAt: '2026-09-18',
  },
  {
    id: 'enq-2',
    enquiryNumber: 'ENQ-2026-00125',
    name: 'Subair K.V.',
    phone: '+91 98470 12345',
    email: 'subair@example.com',
    category: 'MEMBERSHIP',
    message: 'Recently shifted to Mosque Lane. How to transfer my family registration from previous Mahal?',
    status: 'NEW',
    createdAt: '2026-09-21',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-member-1',
    title: 'Monthly Contribution Due for September 2026',
    message: 'Your monthly Mahal contribution of ₹1,000 for September 2026 is pending. Click to pay securely via UPI.',
    type: 'PAYMENT',
    read: false,
    date: '2026-09-10',
    linkUrl: '#payments',
  },
  {
    id: 'notif-2',
    userId: 'user-member-1',
    title: 'Nikah Application Status Update',
    message: 'Nikah application NIK-2026-00124 has advanced to "UNDER_VERIFICATION" stage.',
    type: 'NIKAH',
    read: false,
    date: '2026-09-18',
    linkUrl: '#nikah',
  },
  {
    id: 'notif-3',
    userId: 'user-member-1',
    title: 'Welfare Scholarship Approved',
    message: 'Welfare scholarship WEL-2026-00045 of ₹20,000 has been approved by the committee.',
    type: 'WELFARE',
    read: true,
    date: '2026-08-24',
    linkUrl: '#welfare',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    certificateNumber: 'CERT-MEM-2026-00124',
    type: 'MEMBERSHIP',
    title: 'MAHAL MEMBERSHIP CERTIFICATE',
    memberId: 'MHL-000124',
    memberName: 'Ahamed Basheer',
    familyId: 'FAM-00042',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    issueDate: '2026-09-21',
    validUntil: '2027-09-20',
    issuedBy: 'C.M. Abdul Azeez (General Secretary)',
    verificationHash: 'MH-VER-9821-B892',
    details: {
      HouseName: 'Baitul Noor',
      FamilyHead: 'Ahamed Basheer',
      MembershipYear: '2021',
      Status: 'Active in Good Standing',
    },
  },
  {
    id: 'cert-2',
    certificateNumber: 'CERT-FAM-2026-00042',
    type: 'FAMILY',
    title: 'MAHAL FAMILY REGISTER CERTIFICATE',
    memberId: 'MHL-000124',
    memberName: 'Ahamed Basheer',
    familyId: 'FAM-00042',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    issueDate: '2026-09-21',
    issuedBy: 'C.M. Abdul Azeez (General Secretary)',
    verificationHash: 'FAM-VER-4412-A109',
    details: {
      HouseName: 'Baitul Noor',
      FamilyHead: 'Ahamed Basheer',
      Spouse: 'Fathima Zeenath',
      ChildrenCount: 2,
      ChildrenNames: 'Mohammed Raihan, Aysha Nuha',
      TotalRegisteredMembers: 4,
    },
  },
  {
    id: 'cert-dth-1',
    certificateNumber: 'CERT-DTH-2026-00038',
    type: 'DEATH',
    title: 'OFFICIAL MAHAL DEATH & BURIAL CERTIFICATE',
    memberId: 'MHL-000124',
    memberName: 'Ahamed Basheer',
    familyId: 'FAM-00042',
    mahalName: 'Noor-ul-Huda Juma Masjid & Mahallu Jama-ath',
    issueDate: '2026-09-20',
    issuedBy: 'C.M. Abdul Azeez (General Secretary)',
    verificationHash: 'DTH-VER-8910-K221',
    details: {
      DeceasedName: 'Late K.P. Alavi Haji',
      DeceasedGender: 'Male',
      AgeAtDeath: 74,
      DateOfDeath: '2026-09-18',
      PlaceOfDeath: 'Residence, West Hill, Kozhikode',
      BurialQabarstan: 'Noor-ul-Huda Mahallu Central Qabarstan',
      BurialDate: '2026-09-18 (After Asr Prayers)',
      QabrRegistrationNo: 'QBR-2026-B12',
      ApplicantKin: 'Ahamed Basheer (Son)',
      HospitalRef: 'MED-KKD-2026-9812',
    },
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-21 10:15 AM',
    userEmail: 'admin@demo.mahalconnect.local',
    userName: 'Usthad Abdul Rahman',
    role: 'ADMIN',
    action: 'SYSTEM_SETTINGS_UPDATED',
    entity: 'MAHAL_SETTINGS',
    entityId: 'settings-1',
    details: 'Verified official WhatsApp integration and updated monthly contribution policy.',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-18 03:40 PM',
    userEmail: 'nikah@demo.mahalconnect.local',
    userName: 'K.V. Moideen Kutty',
    role: 'NIKAH_STAFF',
    action: 'NIKAH_STATUS_CHANGED',
    entity: 'NIKAH_APPLICATION',
    entityId: 'NIK-2026-00124',
    details: 'Status changed from DOCUMENTS_RECEIVED to UNDER_VERIFICATION.',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-06 11:24 AM',
    userEmail: 'member@demo.mahalconnect.local',
    userName: 'Ahamed Basheer',
    role: 'MEMBER',
    action: 'ONLINE_PAYMENT_SUCCESS',
    entity: 'PAYMENT_RECORD',
    entityId: 'pay-2026-08',
    details: 'Paid ₹1,000 for August 2026 monthly contribution. Receipt RCT-2026-00084 generated.',
  },
];

export const INITIAL_COUNSELLING_BOOKINGS: CounsellingBooking[] = [
  {
    id: 'couns-1',
    bookingNumber: 'MC-2026-0012',
    applicantName: 'Faisal & Nasreen',
    phone: '+91 98471 22334',
    email: 'faisal.n@example.com',
    type: 'PRE_MARITAL',
    preferredDate: '2026-09-28',
    preferredTimeSlot: '10:30 AM - 11:30 AM',
    mode: 'IN_PERSON',
    notes: 'Pre-marital counselling before upcoming wedding in October.',
    status: 'CONFIRMED',
    createdAt: '2026-09-20',
  },
  {
    id: 'couns-2',
    bookingNumber: 'MC-2026-0013',
    applicantName: 'Abdul Khader K.',
    phone: '+91 94470 88776',
    email: 'khader.k@example.com',
    type: 'FAMILY_HARMONY',
    preferredDate: '2026-09-30',
    preferredTimeSlot: '04:30 PM - 05:30 PM',
    mode: 'IN_PERSON',
    notes: 'Family mediation and mutual agreement reconciliation.',
    status: 'SCHEDULED',
    createdAt: '2026-09-21',
  },
];

export const INITIAL_EDUCATION_REGISTRATIONS: EducationGuidanceRegistration[] = [
  {
    id: 'edu-1',
    regNumber: 'EGC-2026-0041',
    studentName: 'Zayan Mohammed',
    parentName: 'Mohammed Shafi',
    phone: '+91 98460 33445',
    currentClass: 'Plus Two Science',
    targetCareer: 'NEET / Medicine',
    address: 'Baitul Falah, Ward 4, West Hill',
    wardNumber: '4',
    status: 'COUNSELLED',
    createdAt: '2026-09-15',
  },
  {
    id: 'edu-2',
    regNumber: 'EGC-2026-0042',
    studentName: 'Nadha Fathima',
    parentName: 'Mustafa Master',
    phone: '+91 94472 66778',
    currentClass: 'Degree Final Year',
    targetCareer: 'Civil Services / UPSC',
    address: 'Anugraha Manzil, Ward 2',
    wardNumber: '2',
    status: 'REGISTERED',
    createdAt: '2026-09-19',
  },
];

export const INITIAL_BLOOD_DONORS: BloodDonor[] = [
  {
    id: 'donor-1',
    name: 'Suhail P.K.',
    bloodGroup: 'O+',
    phone: '+91 98471 00112',
    age: 27,
    wardNumber: 'Ward 3 (Juma Masjid Ward)',
    lastDonatedDate: '2026-05-10',
    isAvailable: true,
    notes: 'Regular donor, ready for emergency calls in Kozhikode Medical College.',
  },
  {
    id: 'donor-2',
    name: 'Rashid C.H.',
    bloodGroup: 'B+',
    phone: '+91 94470 33445',
    age: 32,
    wardNumber: 'Ward 1 (Beach Road)',
    lastDonatedDate: '2026-06-15',
    isAvailable: true,
    notes: 'Available for platelet donation upon request.',
  },
  {
    id: 'donor-3',
    name: 'Muhammed Nihal',
    bloodGroup: 'A+',
    phone: '+91 98460 77889',
    age: 24,
    wardNumber: 'Ward 4 (Bypass Junction)',
    lastDonatedDate: '2026-07-02',
    isAvailable: true,
    notes: 'Youth volunteer, vehicle available for emergency hospital transport.',
  },
  {
    id: 'donor-4',
    name: 'Dr. Shahir A.',
    bloodGroup: 'AB+',
    phone: '+91 94461 55667',
    age: 38,
    wardNumber: 'Ward 2 (Post Office Road)',
    lastDonatedDate: '2026-04-20',
    isAvailable: true,
    notes: 'Medical practitioner, available for local emergency support.',
  },
  {
    id: 'donor-5',
    name: 'Haris K.V.',
    bloodGroup: 'O-',
    phone: '+91 98475 99881',
    age: 29,
    wardNumber: 'Ward 5 (North Hill)',
    lastDonatedDate: '2026-03-12',
    isAvailable: true,
    notes: 'Rare blood group donor, prioritized for critical emergency cases.',
  },
];

export const INITIAL_BLOOD_REQUESTS: BloodRequest[] = [
  {
    id: 'req-1',
    patientName: 'Kadeejabi (Age 64)',
    hospital: 'Government Medical College Hospital, Kozhikode',
    bloodGroup: 'O+',
    unitsNeeded: 2,
    contactPerson: 'Mujeeb Rahman',
    phone: '+91 98461 44556',
    requiredDate: '2026-09-23',
    urgency: 'URGENT',
    status: 'DONORS_ARRANGED',
    createdAt: '2026-09-21',
  },
];

export const INITIAL_DEATH_CERTIFICATE_APPLICATIONS: DeathCertificateApplication[] = [
  {
    id: 'dth-app-1',
    applicationNumber: 'DTH-2026-00038',
    applicantId: 'MHL-000124',
    applicantName: 'Ahamed Basheer',
    applicantPhone: '+91 98460 11223',
    applicantRelation: 'SON',
    deceasedName: 'K.P. Alavi Haji',
    deceasedGender: 'MALE',
    deceasedAge: 74,
    deceasedMemberId: 'MHL-000089',
    dateOfDeath: '2026-09-18',
    timeOfDeath: '06:15 AM',
    placeOfDeath: 'Residence, West Hill, Kozhikode',
    causeOfDeath: 'Natural Age-Related Demise',
    burialQabarstan: 'Noor-ul-Huda Mahallu Central Qabarstan',
    burialDate: '2026-09-18',
    burialTime: '04:45 PM (After Asr)',
    qabrNumber: 'QBR-2026-B12',
    doctorHospitalCertificateNo: 'MED-KKD-2026-9812',
    status: 'APPROVED',
    certificateId: 'cert-dth-1',
    certificateNumber: 'CERT-DTH-2026-00038',
    createdAt: '2026-09-19',
    approvedAt: '2026-09-20',
  },
  {
    id: 'dth-app-2',
    applicationNumber: 'DTH-2026-00045',
    applicantId: 'MHL-000124',
    applicantName: 'Ahamed Basheer',
    applicantPhone: '+91 98460 11223',
    applicantRelation: 'GUARDIAN',
    deceasedName: 'Fathima Beevi',
    deceasedGender: 'FEMALE',
    deceasedAge: 82,
    dateOfDeath: '2026-09-21',
    timeOfDeath: '11:30 PM',
    placeOfDeath: 'Government Medical College Hospital, Kozhikode',
    causeOfDeath: 'Cardiorespiratory Arrest',
    burialQabarstan: 'Noor-ul-Huda Mahallu Central Qabarstan',
    burialDate: '2026-09-22',
    burialTime: '01:45 PM (After Dhuhr)',
    qabrNumber: 'QBR-2026-C04',
    doctorHospitalCertificateNo: 'MCH-KKD-2026-4412',
    status: 'SUBMITTED',
    createdAt: '2026-09-22',
  },
];

export const INITIAL_FINANCIAL_SUMMARY: InstitutionFinancialSummary = {
  masjidIncomeThisMonth: 185400,
  masjidExpensesThisMonth: 112000,
  masjidProfitThisMonth: 73400,
  madrasaIncomeThisMonth: 94800,
  madrasaExpensesThisMonth: 71500,
  madrasaProfitThisMonth: 23300,
  totalIncomeThisMonth: 280200,
  totalExpensesThisMonth: 183500,
  netProfitThisMonth: 96700,
  currentMonthName: 'September 2026',
};

export const INITIAL_FINANCIAL_LEDGER: FinancialLedgerEntry[] = [
  {
    id: 'led-01',
    date: '2026-09-02',
    institution: 'MASJID',
    type: 'INCOME',
    category: 'Household Monthly Masavari',
    title: 'Ward 1 & 2 Automated UPI Masavari Inflows',
    amount: 68000,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-SEP-001',
    recordedBy: 'Admin Treasury Desk',
    notes: 'Direct online bank settlement',
  },
  {
    id: 'led-02',
    date: '2026-09-04',
    institution: 'MASJID',
    type: 'INCOME',
    category: 'Friday Juma Collection',
    title: 'First Juma Box Collection (4 Gates)',
    amount: 18500,
    paymentMethod: 'CASH',
    referenceNo: 'VCH-SEP-002',
    recordedBy: 'Treasury Counter Unit',
    notes: 'Counted before committee witnesses',
  },
  {
    id: 'led-03',
    date: '2026-09-05',
    institution: 'MADRASA',
    type: 'INCOME',
    category: 'Madrasa Monthly Student Fee',
    title: 'Nursery to 5th Standard Monthly Fees',
    amount: 32000,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-MDR-001',
    recordedBy: 'Madrasa Sadr Mudarris',
  },
  {
    id: 'led-04',
    date: '2026-09-07',
    institution: 'MASJID',
    type: 'EXPENSE',
    category: 'Imam & Khatib Honorarium',
    title: 'Monthly Honorarium for Chief Khatib & Second Imam',
    amount: 38000,
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'VCH-EXP-001',
    recordedBy: 'Committee Secretary',
  },
  {
    id: 'led-05',
    date: '2026-09-08',
    institution: 'MADRASA',
    type: 'EXPENSE',
    category: 'Mudarris (Teacher) Salaries',
    title: 'Salaries for 5 Madrasa Asathidha (Faculty)',
    amount: 48000,
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'VCH-EXP-002',
    recordedBy: 'Madrasa Committee',
  },
  {
    id: 'led-06',
    date: '2026-09-09',
    institution: 'MASJID',
    type: 'INCOME',
    category: 'Household Monthly Masavari',
    title: 'Ward 3 & 4 Counter Collections',
    amount: 50000,
    paymentMethod: 'CASH',
    referenceNo: 'VCH-SEP-003',
    recordedBy: 'Admin Desk',
  },
  {
    id: 'led-07',
    date: '2026-09-11',
    institution: 'MASJID',
    type: 'INCOME',
    category: 'Friday Juma Collection',
    title: 'Second Juma Box & Haris Collection',
    amount: 15700,
    paymentMethod: 'CASH',
    referenceNo: 'VCH-SEP-004',
    recordedBy: 'Treasury Counter Unit',
  },
  {
    id: 'led-08',
    date: '2026-09-12',
    institution: 'MADRASA',
    type: 'INCOME',
    category: 'Madrasa Monthly Student Fee',
    title: '6th to 10th Standard Monthly Fees',
    amount: 26400,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-MDR-002',
    recordedBy: 'Madrasa Office',
  },
  {
    id: 'led-09',
    date: '2026-09-13',
    institution: 'MASJID',
    type: 'EXPENSE',
    category: 'Electricity & KSEB Bill',
    title: 'KSEB Commercial LT Tariff Bill for Masjid & Minaret',
    amount: 28500,
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'VCH-EXP-003',
    recordedBy: 'Finance Desk',
  },
  {
    id: 'led-10',
    date: '2026-09-14',
    institution: 'MADRASA',
    type: 'INCOME',
    category: 'Sponsor-a-Talib Donation',
    title: 'Endowment for 8 Needy & Orphan Students by NRI Forum',
    amount: 24000,
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'VCH-MDR-003',
    recordedBy: 'Baithul Maal Committee',
  },
  {
    id: 'led-11',
    date: '2026-09-15',
    institution: 'MASJID',
    type: 'INCOME',
    category: 'Mosque Donation Box (Haris)',
    title: 'Central Mihrab and Main Courtyard Boxes Count',
    amount: 21200,
    paymentMethod: 'CASH',
    referenceNo: 'VCH-SEP-005',
    recordedBy: 'Executive Committee',
  },
  {
    id: 'led-12',
    date: '2026-09-16',
    institution: 'MASJID',
    type: 'INCOME',
    category: 'Waqf Building Rent',
    title: 'Rent from 4 Commercial Waqf Shops on Mosque Road',
    amount: 12000,
    paymentMethod: 'CHEQUE',
    referenceNo: 'VCH-SEP-006',
    recordedBy: 'Treasury Desk',
  },
  {
    id: 'led-13',
    date: '2026-09-17',
    institution: 'MADRASA',
    type: 'EXPENSE',
    category: 'Textbooks & Syllabus Printing',
    title: 'Half-yearly Question Papers and Islamic History Books',
    amount: 12500,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-EXP-004',
    recordedBy: 'Madrasa Board',
  },
  {
    id: 'led-14',
    date: '2026-09-18',
    institution: 'MASJID',
    type: 'EXPENSE',
    category: 'Muezzin Salary',
    title: 'Monthly Salary for Chief Muezzin & Caretaker',
    amount: 17000,
    paymentMethod: 'BANK_TRANSFER',
    referenceNo: 'VCH-EXP-005',
    recordedBy: 'Secretary Desk',
  },
  {
    id: 'led-15',
    date: '2026-09-19',
    institution: 'MADRASA',
    type: 'INCOME',
    category: 'Kitab & Library Fund',
    title: 'Donation for Islamic Reference Library',
    amount: 12400,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-MDR-004',
    recordedBy: 'Madrasa Board',
  },
  {
    id: 'led-16',
    date: '2026-09-20',
    institution: 'MASJID',
    type: 'EXPENSE',
    category: 'Sanitization & Cleaning',
    title: 'Wudu Khana Disinfectants, Carpets & Restroom Maintenance',
    amount: 14500,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-EXP-006',
    recordedBy: 'Maintenance Committee',
  },
  {
    id: 'led-17',
    date: '2026-09-21',
    institution: 'MASJID',
    type: 'EXPENSE',
    category: 'Sound System Maintenance',
    title: 'Amplifier Servicing, Wireless Mic Battery Replacement',
    amount: 14000,
    paymentMethod: 'CASH',
    referenceNo: 'VCH-EXP-007',
    recordedBy: 'Technical Team',
  },
  {
    id: 'led-18',
    date: '2026-09-21',
    institution: 'MADRASA',
    type: 'EXPENSE',
    category: 'Classroom Utilities',
    title: 'Fan servicing and LED lighting in Block B',
    amount: 6000,
    paymentMethod: 'CASH',
    referenceNo: 'VCH-EXP-008',
    recordedBy: 'Madrasa Committee',
  },
  {
    id: 'led-19',
    date: '2026-09-22',
    institution: 'MADRASA',
    type: 'EXPENSE',
    category: 'Student Refreshments & Programs',
    title: 'Refreshments for Milad Campaign Workshop',
    amount: 5000,
    paymentMethod: 'UPI',
    referenceNo: 'VCH-EXP-009',
    recordedBy: 'Madrasa Committee',
  },
];

